import type { FoodCategory, MenuItem } from "@/types/menu";

/**
 * All content below is original placeholder editorial content for
 * MR_SK EATRIES. This file is the ONLY place menu content is hardcoded —
 * every component in `components/menu/` and every page under
 * `app/(marketing)/menu/` consumes it exclusively through the functions in
 * `lib/api/menu.ts`, never by importing this file directly. That
 * indirection is what lets Sprint 9 swap in real Express/MongoDB-backed
 * data without touching a single component.
 */

export const MENU_CATEGORIES: FoodCategory[] = [
  { slug: "breakfast", name: "Breakfast", description: "Morning classics, done right", itemCount: 2 },
  { slug: "lunch", name: "Lunch", description: "Quick, satisfying midday plates", itemCount: 2 },
  { slug: "dinner", name: "Dinner", description: "Our signature evening menu", itemCount: 2 },
  { slug: "burgers", name: "Burgers", description: "Hand-formed, flame-grilled, no shortcuts", itemCount: 2 },
  { slug: "pizza", name: "Pizza", description: "Wood-fired, thin crust, bold toppings", itemCount: 2 },
  { slug: "chicken", name: "Chicken", description: "Brined, seasoned, cooked low and slow", itemCount: 2 },
  { slug: "seafood", name: "Seafood", description: "Line-caught and simply prepared", itemCount: 2 },
  { slug: "desserts", name: "Desserts", description: "Sweet endings, made in-house", itemCount: 2 },
  { slug: "drinks", name: "Drinks", description: "Crafted cocktails & mocktails", itemCount: 2 },
];

export const MENU_ITEMS: MenuItem[] = [
  // ── Breakfast ──────────────────────────────────────────────
  {
    id: "brk-1",
    slug: "golden-hour-pancakes",
    name: "Golden Hour Pancakes",
    description: "Stacked buttermilk pancakes, whipped honey butter, seasonal berries.",
    longDescription:
      "Three fluffy buttermilk pancakes stacked high, finished with whipped honey butter and a generous helping of seasonal berries. A weekend brunch favorite since day one.",
    category: "breakfast",
    price: 38,
    currency: "GHS",
    rating: 4.7,
    reviewCount: 189,
    prepTimeMinutes: 15,
    tag: "New",
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 82,
    createdAt: "2026-05-02",
    ingredients: ["Buttermilk", "Free-range eggs", "Honey butter", "Seasonal berries", "Maple syrup"],
    nutrition: { calories: 540, proteinGrams: 12, carbsGrams: 78, fatGrams: 18 },
    galleryCount: 3,
  },
  {
    id: "brk-2",
    slug: "smoked-salmon-benedict",
    name: "Smoked Salmon Benedict",
    description: "Poached eggs, house-smoked salmon, hollandaise, toasted brioche.",
    longDescription:
      "Two poached eggs over toasted brioche with house-smoked salmon and a silky lemon hollandaise. A brunch staple with a smoky, savory finish.",
    category: "breakfast",
    price: 52,
    currency: "GHS",
    rating: 4.8,
    reviewCount: 143,
    prepTimeMinutes: 18,
    tag: "Chef's Pick",
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 88,
    createdAt: "2024-03-11",
    ingredients: ["Smoked salmon", "Free-range eggs", "Brioche", "Hollandaise", "Chives"],
    nutrition: { calories: 610, proteinGrams: 28, carbsGrams: 42, fatGrams: 34 },
    galleryCount: 3,
  },

  // ── Lunch ──────────────────────────────────────────────────
  {
    id: "lun-1",
    slug: "ember-roasted-vegetable-plate",
    name: "Ember Roasted Vegetable Plate",
    description: "Fire-charred seasonal vegetables, whipped tahini, toasted seeds.",
    longDescription:
      "A rotating selection of seasonal vegetables charred over open flame, served over whipped tahini and finished with toasted seeds and herb oil.",
    category: "lunch",
    price: 46,
    currency: "GHS",
    rating: 4.6,
    reviewCount: 97,
    prepTimeMinutes: 20,
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 71,
    createdAt: "2023-11-20",
    ingredients: ["Seasonal vegetables", "Tahini", "Toasted seeds", "Herb oil", "Lemon"],
    nutrition: { calories: 410, proteinGrams: 9, carbsGrams: 38, fatGrams: 24 },
    galleryCount: 2,
  },
  {
    id: "lun-2",
    slug: "grilled-chicken-caesar",
    name: "Grilled Chicken Caesar",
    description: "Char-grilled chicken breast, romaine, shaved parmesan, house dressing.",
    longDescription:
      "Crisp romaine tossed in our house Caesar dressing, topped with char-grilled chicken breast, shaved parmesan, and sourdough croutons.",
    category: "lunch",
    price: 54,
    currency: "GHS",
    rating: 4.5,
    reviewCount: 168,
    prepTimeMinutes: 15,
    tag: "Popular",
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 85,
    createdAt: "2022-09-14",
    ingredients: ["Chicken breast", "Romaine", "Parmesan", "Sourdough croutons", "Caesar dressing"],
    nutrition: { calories: 520, proteinGrams: 38, carbsGrams: 22, fatGrams: 28 },
    galleryCount: 2,
  },

  // ── Dinner ─────────────────────────────────────────────────
  {
    id: "din-1",
    slug: "smoked-brisket-bowl",
    name: "Smoked Brisket Bowl",
    description: "12-hour smoked brisket, charred corn, pickled onion, chili oil.",
    longDescription:
      "Beef brisket smoked low and slow for twelve hours, sliced over rice with charred corn, pickled red onion, and a drizzle of house chili oil.",
    category: "dinner",
    price: 68,
    currency: "GHS",
    rating: 4.9,
    reviewCount: 214,
    prepTimeMinutes: 25,
    tag: "Chef's Pick",
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 96,
    createdAt: "2021-06-18",
    ingredients: ["Beef brisket", "Rice", "Charred corn", "Pickled onion", "Chili oil"],
    nutrition: { calories: 780, proteinGrams: 46, carbsGrams: 58, fatGrams: 36 },
    galleryCount: 3,
  },
  {
    id: "din-2",
    slug: "saffron-seafood-risotto",
    name: "Saffron Seafood Risotto",
    description: "Prawns, calamari, and mussels folded into a saffron arborio risotto.",
    longDescription:
      "Creamy saffron arborio risotto folded with prawns, calamari, and mussels, finished with a touch of lemon zest and fresh parsley.",
    category: "dinner",
    price: 82,
    currency: "GHS",
    rating: 4.8,
    reviewCount: 156,
    prepTimeMinutes: 30,
    tag: "Popular",
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 90,
    createdAt: "2023-01-09",
    ingredients: ["Arborio rice", "Prawns", "Calamari", "Mussels", "Saffron", "Parmesan"],
    nutrition: { calories: 690, proteinGrams: 34, carbsGrams: 62, fatGrams: 28 },
    galleryCount: 3,
  },

  // ── Burgers ────────────────────────────────────────────────
  {
    id: "bur-1",
    slug: "smokehouse-double-stack",
    name: "Smokehouse Double Stack",
    description: "Double smashed patty, smoked cheddar, crispy onion, house sauce.",
    longDescription:
      "Two smashed beef patties layered with smoked cheddar, crispy fried onion, pickles, and our house smokehouse sauce on a toasted brioche bun.",
    category: "burgers",
    price: 58,
    currency: "GHS",
    rating: 4.8,
    reviewCount: 201,
    prepTimeMinutes: 16,
    tag: "Popular",
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 93,
    createdAt: "2022-04-02",
    ingredients: ["Beef patty", "Smoked cheddar", "Crispy onion", "Pickles", "Brioche bun"],
    nutrition: { calories: 860, proteinGrams: 44, carbsGrams: 52, fatGrams: 52 },
    galleryCount: 2,
  },
  {
    id: "bur-2",
    slug: "spiced-black-bean-burger",
    name: "Spiced Black Bean Burger",
    description: "House-made black bean patty, avocado, chipotle mayo, pickled slaw.",
    longDescription:
      "A house-made black bean and roasted pepper patty with avocado, chipotle mayo, and a bright pickled slaw on a toasted whole-grain bun.",
    category: "burgers",
    price: 44,
    currency: "GHS",
    rating: 4.5,
    reviewCount: 88,
    prepTimeMinutes: 14,
    isVegetarian: true,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 68,
    createdAt: "2024-08-30",
    ingredients: ["Black beans", "Roasted peppers", "Avocado", "Chipotle mayo", "Pickled slaw"],
    nutrition: { calories: 590, proteinGrams: 18, carbsGrams: 64, fatGrams: 26 },
    galleryCount: 2,
  },

  // ── Pizza ──────────────────────────────────────────────────
  {
    id: "piz-1",
    slug: "wood-fired-margherita",
    name: "Wood-Fired Margherita",
    description: "San Marzano tomato, fresh mozzarella, basil, olive oil.",
    longDescription:
      "A classic done right — San Marzano tomato sauce, fresh mozzarella, torn basil, and a finish of extra virgin olive oil, blistered in our wood-fired oven.",
    category: "pizza",
    price: 62,
    currency: "GHS",
    rating: 4.7,
    reviewCount: 176,
    prepTimeMinutes: 18,
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 84,
    createdAt: "2020-11-05",
    ingredients: ["San Marzano tomato", "Fresh mozzarella", "Basil", "Olive oil", "Pizza dough"],
    nutrition: { calories: 720, proteinGrams: 28, carbsGrams: 84, fatGrams: 30 },
    galleryCount: 2,
  },
  {
    id: "piz-2",
    slug: "spicy-honey-pepperoni",
    name: "Spicy Honey Pepperoni",
    description: "Double pepperoni, chili-infused honey, fresh oregano.",
    longDescription:
      "Double pepperoni over our house tomato base, finished with a drizzle of chili-infused honey and fresh oregano — sweet heat in every bite.",
    category: "pizza",
    price: 68,
    currency: "GHS",
    rating: 4.9,
    reviewCount: 224,
    prepTimeMinutes: 18,
    tag: "Popular",
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 95,
    createdAt: "2023-07-22",
    ingredients: ["Pepperoni", "Tomato base", "Mozzarella", "Chili honey", "Oregano"],
    nutrition: { calories: 810, proteinGrams: 32, carbsGrams: 80, fatGrams: 40 },
    galleryCount: 2,
  },

  // ── Chicken ────────────────────────────────────────────────
  {
    id: "chi-1",
    slug: "cherrywood-smoked-half-chicken",
    name: "Cherrywood Smoked Half Chicken",
    description: "24-hour brined, cherrywood smoked, finished on the grill.",
    longDescription:
      "Half a chicken brined for 24 hours, smoked over cherrywood, and finished on the grill for a crisp skin and smoky, juicy meat throughout.",
    category: "chicken",
    price: 64,
    currency: "GHS",
    rating: 4.8,
    reviewCount: 132,
    prepTimeMinutes: 28,
    tag: "Chef's Pick",
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 87,
    createdAt: "2021-10-01",
    ingredients: ["Whole chicken", "Brine", "Cherrywood smoke", "House spice rub"],
    nutrition: { calories: 640, proteinGrams: 52, carbsGrams: 6, fatGrams: 38 },
    galleryCount: 2,
  },
  {
    id: "chi-2",
    slug: "korean-style-fried-chicken",
    name: "Korean-Style Fried Chicken",
    description: "Double-fried, gochujang glaze, sesame, scallion.",
    longDescription:
      "Double-fried chicken pieces tossed in a sticky gochujang glaze, finished with toasted sesame seeds and fresh scallion.",
    category: "chicken",
    price: 56,
    currency: "GHS",
    rating: 4.9,
    reviewCount: 198,
    prepTimeMinutes: 22,
    tag: "New",
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 91,
    createdAt: "2026-06-10",
    ingredients: ["Chicken", "Gochujang", "Sesame seeds", "Scallion", "Rice flour"],
    nutrition: { calories: 700, proteinGrams: 40, carbsGrams: 48, fatGrams: 36 },
    galleryCount: 2,
  },

  // ── Seafood ────────────────────────────────────────────────
  {
    id: "sea-1",
    slug: "pan-seared-sea-bass",
    name: "Pan-Seared Sea Bass",
    description: "Crispy skin sea bass, brown butter, capers, charred lemon.",
    longDescription:
      "Sea bass fillet seared skin-side down for a crackling crust, finished in brown butter with capers and a charred lemon half.",
    category: "seafood",
    price: 78,
    currency: "GHS",
    rating: 4.8,
    reviewCount: 121,
    prepTimeMinutes: 20,
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 83,
    createdAt: "2022-12-15",
    ingredients: ["Sea bass", "Brown butter", "Capers", "Lemon", "Parsley"],
    nutrition: { calories: 520, proteinGrams: 44, carbsGrams: 4, fatGrams: 34 },
    galleryCount: 2,
  },
  {
    id: "sea-2",
    slug: "chili-lime-grilled-prawns",
    name: "Chili Lime Grilled Prawns",
    description: "Skewered prawns, chili-lime marinade, charred over open flame.",
    longDescription:
      "Jumbo prawns marinated in chili, lime, and garlic, skewered and grilled over open flame until just charred at the edges.",
    category: "seafood",
    price: 66,
    currency: "GHS",
    rating: 4.7,
    reviewCount: 104,
    prepTimeMinutes: 16,
    tag: "Popular",
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 80,
    createdAt: "2024-02-18",
    ingredients: ["Jumbo prawns", "Chili", "Lime", "Garlic", "Cilantro"],
    nutrition: { calories: 380, proteinGrams: 36, carbsGrams: 8, fatGrams: 18 },
    galleryCount: 2,
  },

  // ── Desserts ───────────────────────────────────────────────
  {
    id: "des-1",
    slug: "dark-chocolate-fondant",
    name: "Dark Chocolate Fondant",
    description: "Molten dark chocolate center, salted caramel, vanilla bean ice cream.",
    longDescription:
      "A warm dark chocolate fondant with a molten center, served with a pool of salted caramel and a scoop of vanilla bean ice cream.",
    category: "desserts",
    price: 34,
    currency: "GHS",
    rating: 5.0,
    reviewCount: 241,
    prepTimeMinutes: 12,
    tag: "Popular",
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 97,
    createdAt: "2021-02-14",
    ingredients: ["Dark chocolate", "Butter", "Free-range eggs", "Salted caramel", "Vanilla ice cream"],
    nutrition: { calories: 480, proteinGrams: 7, carbsGrams: 52, fatGrams: 26 },
    galleryCount: 2,
  },
  {
    id: "des-2",
    slug: "passionfruit-cheesecake",
    name: "Passionfruit Cheesecake",
    description: "Baked vanilla cheesecake, passionfruit glaze, toasted coconut.",
    longDescription:
      "A baked vanilla bean cheesecake on a coconut biscuit base, topped with a bright passionfruit glaze and toasted coconut flakes.",
    category: "desserts",
    price: 32,
    currency: "GHS",
    rating: 4.7,
    reviewCount: 112,
    prepTimeMinutes: 10,
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 74,
    createdAt: "2023-05-27",
    ingredients: ["Cream cheese", "Vanilla bean", "Passionfruit", "Coconut biscuit base"],
    nutrition: { calories: 460, proteinGrams: 8, carbsGrams: 44, fatGrams: 28 },
    galleryCount: 2,
  },

  // ── Drinks ─────────────────────────────────────────────────
  {
    id: "dri-1",
    slug: "smoked-old-fashioned",
    name: "Smoked Old Fashioned",
    description: "Bourbon, house bitters, orange oil, finished with cherrywood smoke.",
    longDescription:
      "Bourbon stirred with house bitters and orange oil, finished tableside with a cherrywood smoke for a lingering, aromatic first sip.",
    category: "drinks",
    price: 42,
    currency: "GHS",
    rating: 4.9,
    reviewCount: 128,
    prepTimeMinutes: 6,
    tag: "Chef's Pick",
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 89,
    createdAt: "2021-09-09",
    ingredients: ["Bourbon", "House bitters", "Orange oil", "Cherrywood smoke"],
    nutrition: { calories: 180, proteinGrams: 0, carbsGrams: 6, fatGrams: 0 },
    galleryCount: 1,
  },
  {
    id: "dri-2",
    slug: "spiced-hibiscus-mocktail",
    name: "Spiced Hibiscus Mocktail",
    description: "Hibiscus, ginger, chili syrup, soda, lime.",
    longDescription:
      "A non-alcoholic mocktail built on house hibiscus tea, fresh ginger, a touch of chili syrup, soda water, and lime.",
    category: "drinks",
    price: 28,
    currency: "GHS",
    rating: 4.6,
    reviewCount: 76,
    prepTimeMinutes: 5,
    tag: "New",
    isVegetarian: true,
    isSpicy: true,
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 100,
    popularityScore: 65,
    createdAt: "2026-04-15",
    ingredients: ["Hibiscus tea", "Ginger", "Chili syrup", "Soda water", "Lime"],
    nutrition: { calories: 90, proteinGrams: 0, carbsGrams: 22, fatGrams: 0 },
    galleryCount: 1,
  },
];

export const MENU_PRICE_BOUNDS: [number, number] = [
  Math.min(...MENU_ITEMS.map((item) => item.price)),
  Math.max(...MENU_ITEMS.map((item) => item.price)),
];
